### ISSUE TITLE
🐛 Bug: Empty input message is sent when pressing "Enter"

### ISSUE THREAD

**Issue by eliaskoromilas** [CopilotKit/CopilotKit#1129]
### ♻️ Reproduction Steps

1. Add the `<CopilotChat>` React UI component.
2. On the browser, press **Enter** without an input message.
3. Get the following response:❌ An error occurred. Please try again.

### ✅ Expected Behavior

When input is empty both send button and keyboard events (**Enter**) must be disabled.

### ❌ Actual Behavior

**Enter** key-down event always triggers the `send()` function, even when the send button is disabled. https://github.com/CopilotKit/CopilotKit/blob/75ee220546841fbc183aa5d1c0438621d6d88fc6/CopilotKit/packages/react-ui/src/components/chat/Input.tsx#L64-L69

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/react-ui@1.4.7
├── @copilotkit/runtime@1.4.7
```

### 📄 Logs (Optional)

```shell
Error getting response: [Error: 400 Message content must be non-empty.]
```

**Comment by CodeProcastinator** [comment]
@quest-bot embark

**Comment by CodeProcastinator** [comment]
can i solve this issue

**Comment by TRIPLE-ADE** [comment]
@eliaskoromilas @NathanTarbert would love to work on this

**Comment by CodeProcastinator** [comment]
i have pushed some modified code is it correct ?

**Comment by NathanTarbert** [comment]
@eliaskoromilas, which example or demo are you using to reproduce the error? 
I'm not getting an error if the message is empty and I press submit.

**Comment by eliaskoromilas** [comment]
It appears when using the OpenAI Assistant adapter.

**Comment by NathanTarbert** [comment]
Ok, thanks for the additional context. 
Have you tested any other adapters?

**Comment by suhasdeshpande** [comment]
@eliaskoromilas Thanks for reporting this behavior. I wasn't exactly get the repro. I get appropriate response from LLM if i submit empty response. 
<img width="702" alt="Screenshot 2024-12-16 at 11 53 26 AM" src="https://github.com/user-attachments/assets/b139f888-dc6c-4112-94cf-a97fc8ac5930" />


Are you suggesting we don't submit empty response all together? 

@mme what do you think of this? I think its reasonable to have prevent empty messages.

**Comment by eliaskoromilas** [comment]
I also see no error when using `OpenAIAdapter` but in any case this behavior is not consistent with the send button.

https://github.com/CopilotKit/CopilotKit/blob/75ee220546841fbc183aa5d1c0438621d6d88fc6/CopilotKit/packages/react-ui/src/components/chat/Input.tsx#L83
