### ISSUE TITLE
🚀 Feature Request: had a idea

### ISSUE THREAD

**Issue by qwas982** [CopilotKit/CopilotKit#1153]
### 🎤 Tell us your idea

First, the daily characterization of identifiers, then, based on the identifiers, generate pseudocode. Subsequently, create documentation based on the pseudocode! Finally, diagrams can be created based on the documentation, such as flowcharts, data structure diagrams, algorithm diagrams, mathematical diagrams, and so on, in various forms.

Do you think you understand information from an object faster by looking at a diagram or by reading text?

Moreover, diagrams can be turned into videos, and videos can be transformed into games. This process has only a positive and progressive impact on our understanding of the world and on how large models understand the world!

；-----------------------------------------

**At the same time, I believe that we have already achieved automatic programming-based Natural Language Characters programming and document generation.**

**For example, we can use 4 large models to complete such a process and layout:**

```
#1 Large Model: Trained to proficiently use natural language + mathematical logical reasoning.
#2 Large Model: Trained to proficiently generate code in various programming languages.
#3 Large Model: Trained to excel in code review + black-box testing.
#4 Large Model: Trained to act as a supervisor + memory + Schedule/Dispatch + human assistant and adjutant.
```

**After that, we can combine them into digital humans, and the process is as follows:**

```
Step 1. The human user provides their [idea | thought | task], which is described in natural language.
Step 2. => Passed to Large Model #4, which translates the user's vague natural language into specific natural language.
Step 3. => Then passed to Large Model #1, which translates the specific natural language into precise pseudocode.
Step 4. => Afterwards, passed to Large Model #2, which takes the pseudocode as input and outputs the actual program code.
Step 5. => After receiving the program code, Large Model #3 performs code review + black-box testing. If issues are found, it returns to Large Model #4.
           Large Model #4, based on the situation, either jumps back to Large Model #2 for modification or proceeds to another sequence, enabling automatic debugging.
```

In addition to this, a state browser is also needed, allowing the digital human to capture interrupts from the user.

**Comment by qwas982** [comment]
Scale Law has indeed not hit a wall or failed.
The release of O3 proves this point.
This time, the application of the Scale Law is on the Chain of Thought (COT). A single chain of thought is not enough; multiple chains are needed. These chains combine to form a thought tree, which in turn combines into a thought graph, and then into a thought network. Through gradual iteration, this process eventually approaches the level of Artificial General Intelligence (AGI).
However, it becomes much harder to further enhance the performance of large models.

The next step is the Logical Chain, which is my speculation. It could be called Logical Chain (COL) or Chain of Logical (COL). The Logical Chain is built on top of the Chain of Thought. With a strong foundation of Chain of Thought, the Scale Law can be applied to the Logical Chain. Then, recursively applying the same process:

A single Logical Chain is not enough; multiple chains are needed.

These chains combine to form a Logical Chain Tree.

The Logical Chain Tree combines into a Logical Chain Graph.

The Logical Chain Graph combines into a Logical Chain Network.
Through gradual iteration, this process allows large models to solve all problems in the human world, including the most basic and simple human cognitive problems that are currently unsolvable.
Of course, this process can also be recursive, leading to Artificial Super Intelligence (ASI), which should happen within the next few years.

A recent open-source news story mentioned that after applying the Chain of Thought to 1B and 3B large models, their performance could match that of 8B and 70B models like Llama 3. This suggests that future large models, while maintaining strong intelligence, will gradually shrink in size. I see this as a form of inverse Scale Law. Who says the Scale Law can only do addition and multiplication? Perhaps in the future, hundreds of millions or even tens of millions of parameters will achieve the performance of today's trillion-level large models.

We can construct large models using simple swarm networks instead of simulating dendrites and axons with massive arrays.

**Comment by NathanTarbert** [comment]
Hi @qwas982, I'm not sure how this fits with CopilotKit.
