### ISSUE TITLE
🚀 Feature Request: Empty Service Adapter

### ISSUE THREAD

**Issue by MrCsabaToth** [CopilotKit/CopilotKit#1157]
### 🎤 Tell us your idea

Certain projects would only want the frontend to interface with their backend and nothing else (such as OpenAI, Anthropic, etc, not even local Ollama). An Empty service adapter doesn't call anywhere. As I experienced other adapters also don't call unless you explicitly make calls described in their documentation. But the leanest and most sure way is an empty adapter.

**Comment by MrCsabaToth** [comment]
It is also beneficial to expose a few more classes in case someone wants to implement their own adapter for some reason.

**Comment by NathanTarbert** [comment]
Hi @MrCsabaToth, thanks for adding this feature request and submitting a PR.
