### ISSUE TITLE
Empty reply when action is taken

### ISSUE THREAD

**Issue by RamonGebben** [CopilotKit/CopilotKit#116]
**Describe the bug**
I've made a quick demo testing out the tool as a part of our product but when I ask the "AI" to take an action on my behalf I get an empty reply back.

**To Reproduce**
1. Load CoPilot kit in your app
2. Provide context as demonstrated in the video
3. Let AI preform action
4. See empty reply

**Expected behavior**
Either no reply is send or something like "Sure thing, I've taken the action"

**Screenshots**
![image](https://github.com/CopilotKit/CopilotKit/assets/5405406/c43e7e6e-d895-4bfa-96e6-62c04695204f)

** Browser (please complete the following information):**
 - All browsers

**Additional context**
https://discord.com/channels/1122926057641742418/1174880340733612144/1179420897501777920

**Comment by ataibarkai** [comment]
Thank you for the bug report Ramon
