### ISSUE TITLE
Co Pilot 

### ISSUE THREAD

**Issue by Myahr208** [CopilotKit/CopilotKit#134]
**Documentation description**
A clear and concise description of the documentation wanted.

**Relevant Context**
Where this documentation fits in
1. Existing documentation (see [docs.copilotkit.ai](https://docs.copilotkit.ai)): '...'
2. Object / function / type: '...'
3. filename: '...'

**Comment by sahilborse** [comment]
@Myahr208  can you describe the problem

**Comment by sahilborse** [comment]
/attempt #134 assign it to me
\
