### ISSUE TITLE
Where is the Docs for Chatbot?

### ISSUE THREAD

**Issue by gusye1234** [CopilotKit/CopilotKit#135]
**Documentation description**
Hi, I'm looking for a neat, simple ChatBot UI in React, and really happy tha found this project.
However, the docs site seems [place the docs of `textarea` in `chatbot`](https://docs.copilotkit.ai/getting-started/quickstart-chatbot). How can I read more about how to use the Chatbot UI of CopilotKit?

**Comment by ataibarkai** [comment]
Thank you @gusye1234! indeed the documentation is missing.
