### ISSUE TITLE
Change `content-type` header for POST requests from "text/plain;charset=UTF-8" to `application/json`

### ISSUE THREAD

**Issue by arjshiv** [CopilotKit/CopilotKit#136]
**Describe the bug**
If the request content type header is not set to `application/json` , common API frameworks like `express` with `body-parser` cannot parse it

**To Reproduce**
1. Set up `CopilotTextArea`
2. Send a request to an `express` server with `body-parser` middleware enabled [ really common for JSON ]
3. Try and parse the body with `req.bod`
4. `req.body` is empty

**Expected behavior**
I expect 

**Screenshots**

** Browser (please complete the following information):**
 - Universal

**Additional context**
 - Sending JSON as `json` is a standard convention, this could break not just Express but most other frameworks.

**Comment by iamtouha** [comment]
@ataibarkai I would like to work on this issue.

**Comment by ataibarkai** [comment]
Great @iamtouha , let me know if you need any support

**Comment by iamtouha** [comment]
Certainly! Could you please specify which files I should be looking at to apply the changes.

**Comment by nsvoriginals** [comment]
Is this bug done?
