### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by mme** [CopilotKit/CopilotKit#145]
**Is your feature request related to a problem? Please describe.**
The chat UI does not support mobile devices

**Describe the solution you'd like**
Make the UI responsive. Respond to keyboard events by moving the text input.

**Comment by Myahr208** [comment]
[myahr208gh repo clone `CopilotKit/CopilotKit](url)`

**Comment by Myahr208** [comment]
<co,pilot><`π`|π-;>

**Comment by RohanMishra315** [comment]
hey @mme should I take a look ?

**Comment by RohanMishra315** [comment]
Hey @mme Sorry to ask , but can you tell me in more detail about the issue and what task should be implemented? Thank you , If not here , we can also discuss these into discord.
