### ISSUE TITLE
Cannot reliably specify array argument type when using useMakeCopilotActionable

### ISSUE THREAD

**Issue by mme** [CopilotKit/CopilotKit#153]
**Describe the bug**

When using `AnnotatedFunctionArrayArgument` and setting `type` of `items` to `"object"`, CopilotKit calls the function with `undefined` as argument. Setting `type` to `"string"` sometimes calls with an object, sometimes with a string as argument.

**To Reproduce**

Try this snippet:

```typescript
  useMakeCopilotActionable(
    {
      name: "addRows",
      description: "Add rows to the current table data",
      argumentAnnotations: [
        {
          name: "rows",
          type: "array",
          items: {
            type: "string",
          },
          description: "The rows to add to the current table data.",
          required: true,
        },
      ],
      implementation: async (rows) => {
        console.log("addRows", rows);
      },
    },
    []
  );
```

**Expected behavior**
When setting type to `"object"`, I expect to get an array of objects, not undefined. In the case of "string", I expect to get an array of strings all the time

**Comment by RohanMishra315** [comment]
Yeah @mme I also came across these bug , let me look into these !

**Comment by mme** [comment]
Awesome @RohanMishra315 !!

**Comment by mme** [comment]
@RohanMishra315 it would be already super useful to understand why specifying `"object"` as the array item type returns `undefined`

Let me know if you need any help 👍

**Comment by RohanMishra315** [comment]
If specifying "object" as the type for array items is resulting in undefined being passed to the implementation function, it suggests there might be an issue with how the useMakeCopilotActionable or related functions handle object types. Could you help a bit !
