### ISSUE TITLE
The input field does not focus automatically when opening the chat UI

### ISSUE THREAD

**Issue by mme** [CopilotKit/CopilotKit#172]
**Describe the bug**
The input field does not focus automatically when opening the chat UI

**To Reproduce**
1. Make sure the chat UI is closed
2. Click the button to open it
3. The input field is not focused

**Expected behavior**
The input field should focus when the chat UI is opened

** Browser (please complete the following information):**
 - Mac / Safari

**Comment by iwint** [comment]
Can you assign this to me ?

**Comment by mme** [comment]
Hey @iwint thanks for helping out.

**Comment by mme** [comment]
Hi @iwint do you still want to contribute to this issue?
