### ISSUE TITLE
Extra space at the bottom of the initial message

### ISSUE THREAD

**Issue by mme** [CopilotKit/CopilotKit#190]
**Describe the bug**
There is some extra space at the bottom of the initial message

**To Reproduce**
1. Open the Hello World demo

**Expected behavior**
There should not be any extra whitespace

**Screenshots**
<img width="440" alt="image" src="https://github.com/CopilotKit/CopilotKit/assets/247775/97f52546-225d-40e9-ac87-f35423ad314c">

** Browser (please complete the following information):**
 - Mac / safari

**Comment by manasadepu** [comment]
First time contributor here, is this still available?

**Comment by mme** [comment]
@manasadepu yes it is still available.

Hint: This should ideally be fixed in the CSS - the last element of a`.copilotKitMarkdown` child should not have a bottom margin.

Thank you for your help!

**Comment by mme** [comment]
Hi @manasadepu do you still want to contribute to this issue?
