### ISSUE TITLE
Add an option to open the link in a new tab for rendering message result

### ISSUE THREAD

**Issue by JimmyLv** [CopilotKit/CopilotKit#277]
**Describe the bug**
When rendering the results of a Markdown message, if there is a link, it needs to be opened by the user in a new window, otherwise it will disrupt the current state of the site, such as when the user is in the middle of an action in the main application and is typing something.        

**Additional context**

https://github.com/remarkjs/react-markdown/issues/65#issuecomment-799681920

https://github.com/rehypejs/rehype-external-links

**Comment by ataibarkai** [comment]
Fixed in the latest release ✅
