### ISSUE TITLE
Backend in NestJS 

### ISSUE THREAD

**Issue by apperside** [CopilotKit/CopilotKit#295]
**Describe the bug**
Hi, 
first of all thanks a lot for this fantastic piece of software!
I have managed to integrate it in my NextJS app, I can see the chat sidebar appearing and the chat content be posted to my NestJS backend, where I am handling the request this way

```
  @Post('/chat')
  public async chat(
    @Request() request,
    @Response() response,
  ) {
    const copilotKit = new CopilotBackend();

    const result = await copilotKit.response(
      request,
      new OpenAIAdapter(),
    );
    return result
  }
```

I also have tried this

```
  @Post('/chat')
  public async chat(
    @Request() request,
    @Response() response,
  ) {
    const copilotKit = new CopilotBackend();

    const result = await copilotKit.stream(
      request,
      new OpenAIAdapter(),
    );
    return result
  }
```

and this 

```

  @Post('/chat')
  public async chat(
    @Request() request,
    @Response() response,
  ) {
    const copilotKit = new CopilotBackend();

    const result = await copilotKit.streamHttpServerResponse(
      request,
      response,
      new OpenAIAdapter(),
    );
    return result
  }
```

By in any case the chat waits for the response indefinitely. By adding some breakpoint, the response is properly generated, but for some reason the clients does not receive it. 
What am I missing?

Many thanks

**Comment by ikudev** [comment]
@apperside Hello, I think you should write your nestjs code like this:
```ts
@Post('chat')
  async chat(
    @Req() request: Request,
    @Res() response: Response,
  ): Promise<void> {
    const copilotKit = new CopilotBackend();
    await copilotKit.streamHttpServerResponse(request, response, new OpenAIAdapter());
  }
```
Because `streamHttpServerResponse` returns `Promise<void>`, you can't get anything using its return value.
You should completely delegate everything to the `CopilotBackend` instance.

BTW, the above code is a simple version to demonstrate something. It'll be better to create the `CopilotBackend` instance in a service instead, in case of creating a new instance every time a request comes.

**Comment by ikudev** [comment]
Please refer to this demo I made.
https://github.com/ikudev/copilotkit-nestjs-demo

**Comment by NathanTarbert** [comment]
Thanks @ikudev for hopping in here to help. 
Much appreciated!
