### ISSUE TITLE
example folder is wrong.

### ISSUE THREAD

**Issue by FingerLiu** [CopilotKit/CopilotKit#304]
the example seems misconfigured, and can not get it run

**Comment by FingerLiu** [comment]
Tried https://github.com/CopilotKit/example_app-todo , can't get a response from openai, either. Is the examples out-of-date or under re-construction?

**Comment by ikudev** [comment]
@FingerLiu 
As this repo is managed using Turborepo, you can run `pnpm i && pnpm dev --filter next-openai` to start the example app of `next-openai`. Then you can access `http://localhost:3000` to view the app!
