### ISSUE TITLE
Custom buttons under bot response

### ISSUE THREAD

**Issue by ogoldberg** [CopilotKit/CopilotKit#380]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to include custom buttons under the response from a bot in order to collect feedback or take other actions, similar to how ChatGPT does it
![image](https://github.com/CopilotKit/CopilotKit/assets/127390/252db6b1-f807-43aa-b06c-d068d3e0cad2)

**Describe the solution you'd like**
If this is already possible, can you please help me understand how to do it and maybe update the docs to be more explicit about this feature?
If not, can you please create the ability to set some buttons and actions to accompany a bot's response?

**Describe alternatives you've considered**
I have considered not having this feature and I have considered not using copilotkit so that I can have this feature.

**Additional context**
Here's a screenshot of what ChatGPT's buttons look like under a bot response.
![image](https://github.com/CopilotKit/CopilotKit/assets/127390/e51f8b13-b0eb-4790-8a53-57043b2cc7bb)

**Comment by mme** [comment]
Hey @ogoldberg , thanks your description of alternatives, made me laugh!

As for custom buttons below the assistant message, CopilotKit allows you to swap out the components for UI elements so you can provide your own.

In this case, you can customize the `ResponseButton` to get what you want.

For example:
```tsx
const CustomResponseButton = ({ onClick, inProgress }: ResponseButtonProps) => {
  return (
    <div style={{ display: "flex", marginTop: "10px" }}>
      <button
        style={{ flex: 1, border: "1px solid #eee", borderRadius: "4px", marginRight: "5px" }}
      >
        👍
      </button>
      <button style={{ flex: 1, border: "1px solid #eee", borderRadius: "4px" }}>👎</button>
    </div>
  );
};
```

And then passing this to `CopilotSidebar`:

```tsx
<CopilotSidebar ResponseButton={CustomResponseButton}>
...
</CopilotSidebar>
```

Would give you this result:

<img width="444" alt="image" src="https://github.com/CopilotKit/CopilotKit/assets/247775/5d232638-9e2a-4b93-8717-4165eefb3769">

Let me know if this helps.

**Comment by ogoldberg** [comment]
Thank you! Very helpful!
