### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ghost** [CopilotKit/CopilotKit#466]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (the easier it is to replicate, the sooner it will get fixed):

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Environment:**

- OS/Browser: [e.g. MacOS/Safari, Windows/Chrome, iOS/Safari]
- Runtime: [Copilot Cloud, self-hosted]
- Frontend Framework: [e.g. Next, Remix]
- Backend Framework (if self-hosted): [e.g. Next, Node, Firebase]

**CopilotKit Packages**
Add the output of this command:

```sh
cat **/package.json | grep "@copilotkit"
```

**Frontend Code**
Provide any code related to the issue, especially CopilotKit components and hooks.

```tsx
<CopilotKit>
  <CopilotPopup instructions="...">
    ...
  </CopilotPopup>
</CopilotKit>

useCopilotReadable({
  description: "Your Description...",
  value: aValue,
})

useCopilotAction({
  ... your action config
})
```

**Backend Code**

If you self-host the runtime, please provide the relevant backend code.
For example, provide your server side actions:

```ts
const copilotKit = new CopilotRuntime({
  actions: [
    // ... your actions
  ],
});
// ... your server side code
```

**Comment by Nitingirlsavenue1** [comment]
Create issue

**Comment by NathanTarbert** [comment]
Hi @ddemaree, apologies for the delay. 
Are you still having issues?

**Comment by ddemaree** [comment]
@NathanTarbert I don't think I filed this bug?

**Comment by NathanTarbert** [comment]
Hey @ddemaree, apologies, that's correct, thank you!
