### ISSUE TITLE
⭐ 01 - Weather Forecasting Bot (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#602]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Build a chatbot that gives real-time weather updates using CopilotKit's AI interaction capabilities.

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by nooras** [comment]
Hi @NathanTarbert 
I am interested in this task. Can you please assign me ?
Also can you please share documentation or how to build a chatbot? How to submit it ?

**Comment by NathanTarbert** [comment]
@nooras, thank you for your interest. 
We will start assigning tomorrow when Hacktoberfest officially kicks off.
I will add a link to the instructions from our Hacktoberfest rules later today.

**Comment by NathanTarbert** [comment]
@SGCODEX & @nooras, please follow the link at the top to get started!

**Comment by SGCODEX** [comment]
Thank you @NathanTarbert Sir, will get started.

**Comment by nooras** [comment]
Hi @NathanTarbert 
there is no such file as template here
https://github.com/CopilotKit/CopilotKit/blob/main/.TEMPLATE.md
![image](https://github.com/user-attachments/assets/da744a89-4c42-40e2-ada1-9fe1ecc8051d)

Also it would be great if u could provide any example.

**Comment by NathanTarbert** [comment]
Hi @nooras, apologies, there was a typo that affected the route. Please try again

**Comment by NathanTarbert** [comment]
The demo folder is at the root of the `community` folder - https://github.com/CopilotKit/CopilotKit/tree/main/community

**Comment by NathanTarbert** [comment]
I will fix it

**Comment by JanumalaAkhilendra** [comment]
I want to work on this issue :) , please assign it to me .
Thank you.

**Comment by FaheemOnHub** [comment]
Hi @NathanTarbert
I'd like to work on this

**Comment by himanshubalani** [comment]
Hey, I'd like to work on this too

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , Please assign this task to me.

**Comment by Army-cloud-95** [comment]
@NathanTarbert .please assign me this issue

**Comment by NathanTarbert** [comment]
Hi @Army-cloud-95, this was an issue for Hacktoberfest.

**Comment by Army-cloud-95** [comment]
yes i want to work
