### ISSUE TITLE
⭐ 03 - Task Manager (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#604]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Design a simple task management app where users can create, update, and delete tasks using voice or text commands

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)
- 
![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Vaibhav91one** [comment]
I would like to work on this @NathanTarbert.

**Comment by Shubham66020** [comment]
@NathanTarbert please assign this to me

**Comment by Code-Hacker26** [comment]
Hey @NathanTarbert, I’m really eager to work on this issue. Could you please assign it to me?

**Comment by FaheemOnHub** [comment]
@NathanTarbert please assign this to me

**Comment by Sumith540** [comment]
please assign me. this

**Comment by princerafid01** [comment]
@NathanTarbert I would like to contribute to this. Can you assign me this?

**Comment by FaheemOnHub** [comment]
@quest-bot embark

**Comment by Vaishnavi-Raykar** [comment]
Hi @NathanTarbert...I had already worked on this issue please assign this to me.
