### ISSUE TITLE
⭐ 04 - Travel Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#605]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

## Description
Develop a travel app that recommends locations and landmarks based on your travel plans

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by ShreemaRavi** [comment]
Hello,I'm interested in working on this.Could you please assign to me

**Comment by uvenkatateja** [comment]
Hi @NathanTarbert

I would like to help with the Travel Planner demo for Hacktoberfest. Could you please assign this issue to me?

**Comment by AJBrownson** [comment]
@NathanTarbert 
I'd like to work on this

**Comment by devshah207** [comment]
I would like to contibute to this. Can you assign me this?

**Comment by princerafid01** [comment]
@NathanTarbert I would like to contibute to this. Can you assign me this?
