### ISSUE TITLE
⭐ 05 - Event Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#606]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Create a tool where users can plan events by asking for date suggestions, locations, and activities.

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Zedoman** [comment]
please assign this to me i can work on this issue efficiently.

**Comment by NathanTarbert** [comment]
@Zedoman, please follow the link at the top to get started!

**Comment by Zedoman** [comment]
Ok sir Thanks a lot....

**Comment by Zedoman** [comment]
Sir submitter the PR https://github.com/CopilotKit/CopilotKit/pull/695

**Comment by AJBrownson** [comment]
@NathanTarbert 
I'd like to work on this

**Comment by ChiragAgg5k** [comment]
@quest-bot embark
