### ISSUE TITLE
⭐ 07 - Daily Quote App (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#608]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Create a daily motivational quote app where users can request quotes or share their own

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Redidacove** [comment]
@NathanTarbert can you assign it to me

**Comment by Redidacove** [comment]
Sure ser

**Comment by NathanTarbert** [comment]
@Redidacove, please follow the link at the top to get started!

**Comment by Redidacove** [comment]
sure @NathanTarbert thanks for assigning me this I hope will be able to complete it soon in case need help where can we chat

**Comment by Arpit-Khandelwal** [comment]
I would like to work on this! Can you assign it to me @NathanTarbert

**Comment by nitesh2920** [comment]
If this is still open can i work on this @NathanTarbert

**Comment by AJBrownson** [comment]
@NathanTarbert 
I'd like to work on this

**Comment by Jiamir** [comment]
I want to work on this!

**Comment by yaarAdarsh** [comment]
@NathanTarbert   can you assign me this . I want to work on this!

**Comment by Ruffzi069** [comment]
Hey @NathanTarbert ! I think I will be able to contribute in this issue. Can you assign me this?
Thank you!

**Comment by nitesh2920** [comment]
@quest-bot embark

**Comment by Vaishnavi-Raykar** [comment]
@NathanTarbert....I'm interested.

**Comment by nitesh2920** [comment]
@NathanTarbert #846

**Comment by nitesh2920** [comment]
@quest-bot embark

**Comment by nitesh2920** [comment]
@quest-bot loot #846

**Comment by nitesh2920** [comment]
@quest-bot embark

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , please assign this task to me.
