### ISSUE TITLE
⭐ 08 - Language Translator (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#609]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Build a simple translator that converts sentences from one language to another using natural language queries

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by lasj123** [comment]
Hey @NathanTarbert 
Can you please assign this to me?

**Comment by NathanTarbert** [comment]
@lasj123, we will officially kick off Hacktoberfest tomorrow. 
I will post a link to the rules and guidelines later today.

**Comment by NathanTarbert** [comment]
@lasj123, please follow the link at the top to get started.

**Comment by Mayank77maruti** [comment]
Hi @NathanTarbert , can you assign this task to me.

**Comment by Vaishnavi-Raykar** [comment]
I'm interested... @NathanTarbert , can you please assign me this issue

**Comment by kushal34712** [comment]
@NathanTarbert  i am interested , can u plz assign me this issue

**Comment by anshuman-rai-27** [comment]
can you plz assign me this issue ? i have create the app will be pushing the pr after being assigned

**Comment by Vaishnavi-Raykar** [comment]
@quest-bot embark

**Comment by Mayank77maruti** [comment]
@quest bot embark

**Comment by PriyanshuDas01** [comment]
Hey @NathanTarbert , please assign this task to me.
I would love to make a pr.

**Comment by Mayank77maruti** [comment]
@quest-bot embark

**Comment by kushal34712** [comment]
@quest-bot loot #766
