### ISSUE TITLE
⭐ 10 - Music Playlist Generator (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#611]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Create an app that generates personalized music playlists based on mood, genre, or recent listening history

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by aniirathod** [comment]
How to submit the application ?

**Comment by Saedbhati** [comment]
Can I assign these to me?

**Comment by NathanTarbert** [comment]
Hi @aniirathod & @Saedbhati, we will officially kick Hacktoberfest off tomorrow. 
I will post a link to the guidelines later today.

**Comment by Saedbhati** [comment]
@NathanTarbert any updates?

**Comment by NathanTarbert** [comment]
@Saedbhati, please follow the link at the top to get started!

**Comment by aniirathod** [comment]
@NathanTarbert can you assign this project to me ?

**Comment by Shubham66020** [comment]
@NathanTarbert please assign this to me

**Comment by aniirathod** [comment]
hey @Shubham66020 do you want to collab with me on this project ?
