### ISSUE TITLE
📚 Documentation: Issue due to having different pages of documentation open in multiple browser windows

### ISSUE THREAD

**Issue by md-abid-hussain** [CopilotKit/CopilotKit#619]
### 💬 Let us know how we can improve our documentation.

![image](https://github.com/user-attachments/assets/0472dbec-2441-42b8-979a-fdf850e06ecc)
![image](https://github.com/user-attachments/assets/d509bdfc-3cbc-4eda-8a19-23c7dacf1de9)

When opening different pages of the documentation site in two separate browser windows, both pages attempt to modify the same variable, `copilotkit-tailored-content` in local storage. This conflict prevents changes from being reflected correctly on the page when selecting different sections using the buttons. As a result, users are unable to update or view the intended content effectively.

### Steps to product this bug/issue
Open [Quickstart: Chatbot](https://docs.copilotkit.ai/quickstart-chatbot) in the first tab and [Introduction to CoAgents](https://docs.copilotkit.ai/coagents) in another tab and try changing the above button in the image. It will not work, and if we inspect the variables in local storage, we can see that those variables are repeatedly changing.

### Personal Note
I believe it's important to address this issue, as many developers may have different pages of documentation open in separate tabs while creating an app to quickly reference various sections.

**Comment by PRIYANKjakharia** [comment]
i can work on it

**Comment by md-abid-hussain** [comment]
This is no longer valid since the documentation has changed completely.
