### ISSUE TITLE
Interactive Demo Not Loading in "Textarea Tutorial" Page

### ISSUE THREAD

**Issue by Mohiit70** [CopilotKit/CopilotKit#620]
The interactive demo for the "CopilotKit Todo List Copilot Demo" on the [Textarea Tutorial Overview page](https://docs.copilotkit.ai/tutorial-textarea/overview) is not loading properly. The placeholder image appears with no content, preventing users from testing the demo in real-time.

![image](https://github.com/user-attachments/assets/1cb553c4-ff37-407e-a673-6d8d2ff9a2dc)

**Comment by fadkeabhi** [comment]
Its an issue with CORS. https://example-todos-app.vercel.app/ does not have CORS enabled for for https://docs.copilotkit.ai/ domain. The CORS are only enabled for localhost.
