### ISSUE TITLE
⭐ 11 - Budget Tracker (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#623]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Build a financial budgeting tool that helps users track expenses and savings goals with text-based inputs

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by AdityaGupta20871** [comment]
Hi @NathanTarbert I am currently working on this project using shadcn-ui and copilot-kit for the quira quest. Can you assign it to me! :)

**Comment by rohitprasad-code** [comment]
Hey @NathanTarbert I want to work on this, can you kindly assign me this issue?

**Comment by Ruffzi069** [comment]
I would like to contribute in this as well !
Can you assign me this ?

**Comment by abhirajadhikary06** [comment]
🍀Hey @NathanTarbert can you assign this to me as well !

**Comment by TRIPLE-ADE** [comment]
Please assign this to me I already have it in the pipeline
