### ISSUE TITLE
⭐ 12 - Travel Itinerary Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#624]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description
Design an app where users can ask for suggested travel destinations and itineraries for upcoming trips

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by sambhavnrana** [comment]
Kindly assign me this issue so that I start contributing to it.

**Comment by MOHDNEHALKHAN** [comment]
@NathanTarbert , can you assign me to this issue

**Comment by RS-labhub** [comment]
I want to take this up!

**Comment by sambhavnrana** [comment]
Can I also contribute to it @NathanTarbert

**Comment by FaheemOnHub** [comment]
hi @NathanTarbert  can u assign me this ?

**Comment by Ruffzi069** [comment]
Hey @NathanTarbert ! I want to contribute in this !
Can you please assign me this!
Thank you!
