### ISSUE TITLE
⭐ 15 - News Aggregator (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#627]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create an app that summarizes the latest news articles based on user-specified topics or keywords
#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by anshuman-rai-27** [comment]
hey can you plz assign me this issue ?

**Comment by PriyanshuDas01** [comment]
Hey the idea seems intresting to me, also I have a similar ongoing project so I think I can add valuable input on this one. Can you please assign me this issue?

**Comment by Tejas-Sharma-dev** [comment]
Hi @NathanTarbert,

I'm also interested in working on this issue. can i go ahead?

**Comment by fadexadex** [comment]
Please assign this issue to me as well

**Comment by fadexadex** [comment]
Please how do I get the open ai api keys without having to pay?

**Comment by NathanTarbert** [comment]
@fadexadex, I haven't tried this but you can potentially use a proxy with 3.5
https://www.youtube.com/watch?v=giYejigUM9A
Let me know if this works.

**Comment by fadexadex** [comment]
I was thinking of maybe using groq.

**Comment by fadexadex** [comment]
@quest-bot embark

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , please assign this task to me.

**Comment by Mayank77maruti** [comment]
@quest-bot embark
