### ISSUE TITLE
⭐ 16 - AI-powered FAQ Bot (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#628]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Build a FAQ bot for websites that answers common customer questions

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by md-abid-hussain** [comment]
I would like to work on this.

**Comment by AJBrownson** [comment]
Hi @NathanTarbert 
I'd like to work on this

**Comment by AmalFrancisOlakengil** [comment]
Hey @NathanTarbert Can I work on this?

**Comment by arkokundu500** [comment]
I would like to work on this, please assign me @NathanTarbert

**Comment by FaheemOnHub** [comment]
@NathanTarbert can u assign me this ?

**Comment by AkashJana18** [comment]
@quest-bot embark
