### ISSUE TITLE
⭐ 17 - Interactive Flashcards (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#629]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create a learning app that allows users to create flashcards for studying and quizzes them interactively

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Niharika0104** [comment]
Can you assign this issue to me?

**Comment by faheem2312** [comment]
Hello, can you assign me this issue?!!

**Comment by Niharika0104** [comment]
@NathanTarbert Will the best demo be merged or all the presented demos will be merged?

**Comment by NathanTarbert** [comment]
@Niharika0104, if the demo works and utilizes CopilotKit we will merge it.

**Comment by Niharika0104** [comment]
@NathanTarbert demo works perfectly..you can check it out

**Comment by NathanTarbert** [comment]
I sure will @Niharika0104. We are working through all of them.

**Comment by yaarAdarsh** [comment]
@NathanTarbert, can you assign me this. I want to contribute .

**Comment by sanketshinde3001** [comment]
@NathanTarbert Interested.

**Comment by sanketshinde3001** [comment]
@quest-bot embark

**Comment by Niharika0104** [comment]
@quest-bot embark

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , please assign this task to me.
