### ISSUE TITLE
⭐ 18 - Movie Suggestion Bot (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#630]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Build a bot that recommends movies based on genre, mood, or a user’s previous watch history

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by kom-senapati** [comment]
I would like to solve this issue

**Comment by aniirathod** [comment]
@NathanTarbert can you assign to me ?

**Comment by NathanTarbert** [comment]
Yes, you can take this Issue and collab on a team in devfest.ai

**Comment by NathanTarbert** [comment]
Just follow the link at the top of the issue to get started

**Comment by kom-senapati** [comment]
> Yes, you can take this Issue and collab on a team in devfest.ai

He is not my team mate. Also he didn't reply ...

**Comment by aniirathod** [comment]
@kom-senapati  Hey sorry for the delay, can we proceed together on this project ?

**Comment by kom-senapati** [comment]
> @kom-senapati Hey sorry for the delay, can we proceed together on this project ?

Ok msg me at discord we can proceed together. `komsenapati` my username

**Comment by kom-senapati** [comment]
> @kom-senapati Hey sorry for the delay, can we proceed together on this project ?

Or you can message in this thread in copilotkit discord channel
https://discord.com/channels/1122926057641742418/1291070835783761991

**Comment by NathanTarbert** [comment]
If you both want to collaborate, I would join DevFest AI and put a team together

**Comment by kom-senapati** [comment]
> If you both want to collaborate, I would join DevFest AI and put a team together

I am in another team and its full lol

**Comment by kom-senapati** [comment]
I have started working but if he messages me I can share codebase

**Comment by FaheemOnHub** [comment]
@NathanTarbert  can u assign me this issue

**Comment by FaheemOnHub** [comment]
@quest-bot embark

**Comment by kom-senapati** [comment]
@quest-bot embark
