### ISSUE TITLE
⭐ 19 - Habit Tracker (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#631]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Develop a simple habit tracker that allows users to log their daily habits and set reminders

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by chandanSahoo-cs** [comment]
Can you please assign me this issue

**Comment by PriyanshuDas01** [comment]
Hey I would really like to work on this idea. Can you please assign me this issue?

**Comment by AmalFrancisOlakengil** [comment]
Hey @NathanTarbert I think I can work on this, Can you assign me?

**Comment by subah2004** [comment]
Hi. I think I can work on this. Can you kindly assign me this issue?

**Comment by TejasNarkhede** [comment]
Hey can i still participate?
I wish to work on this issue! can i still get assigned by any chance?
