### ISSUE TITLE
⭐ 20 - Email Organizer (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#632]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create an email management tool that helps users categorize and prioritize emails based on urgency and content

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Code-Hacker26** [comment]
Hey @NathanTarbert, I’m interested in working on the Email Organizer demo, where users can categorize and prioritize emails based on urgency and content. Can you assign it to me ?

**Comment by Rishikesh63** [comment]
@alexandredev3  and @Code-Hacker26  can we work together on this project to complete it early

**Comment by Code-Hacker26** [comment]
> @alexandredev3 and @Code-Hacker26 can we work together on this project to complete it early

@Rishikesh63 sure I am in.

**Comment by alexandredev3** [comment]
> @alexandredev3  and @Code-Hacker26  can we work together on this project to complete it early

Sure!

**Comment by Rishikesh63** [comment]
@NathanTarbert is it looks like as 
![Screenshot 2024-10-15 012756](https://github.com/user-attachments/assets/02894b5a-72be-4614-9f5f-b0e41b8dbc86)

**Comment by Rishikesh63** [comment]
or it is looks like 
![Screenshot 2024-10-15 013952](https://github.com/user-attachments/assets/47c6c8e1-3641-4e0b-b70e-211436db3f3f)

**Comment by Rishikesh63** [comment]
@NathanTarbert  is i need to deploye it on vercel or just make pull request

**Comment by NathanTarbert** [comment]
@Rishikesh63, deploying is a much easier process to check out your app.

**Comment by Rishikesh63** [comment]
@NathanTarbert  I deployed  my Email-organizer project
https://email-organizer-7vs97j141-rishikesh-maddhesiyas-projects.vercel.app/

**Comment by NathanTarbert** [comment]
Hi @Rishikesh63, the link you provided isn't your deployed app, but that's ok. Just add it to the PR

**Comment by Rishikesh63** [comment]
@NathanTarbert  is i need to add whole project or only markdown file ?

**Comment by NathanTarbert** [comment]
Hi @Rishikesh63, just add the markdown file and list your project inside the demos folder https://github.com/CopilotKit/CopilotKit/tree/main/community/demos

**Comment by Rishikesh63** [comment]
> Hi @Rishikesh63, just add the markdown file and list your project inside the demos folder https://github.com/CopilotKit/CopilotKit/tree/main/community/demos

I have added it yesterday

**Comment by Rishikesh63** [comment]
@NathanTarbert  when will my PR merge ?

**Comment by Rishikesh63** [comment]
@NathanTarbert Do I need to close the PR in which I pulled my whole email-organizer project?

**Comment by NathanTarbert** [comment]
@Rishikesh63, I will be reviewing PR's later today and tomorrow.

**Comment by Rishikesh63** [comment]
@quest-bot loot #632

**Comment by Rishikesh63** [comment]
@quest-bot embark
