### ISSUE TITLE
⭐ 24 - Travel Budget Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#636]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Design a tool that helps users plan a budget for their trips, including airfare, lodging, and activities

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by vijaykr338** [comment]
can you assign this to me? I am a beginner

**Comment by NathanTarbert** [comment]
@vijaykr338, please follow the link at the top to get started.

**Comment by RohittCodes** [comment]
@NathanTarbert, I would like to work on this.

**Comment by harshitajha4680** [comment]
I would like to work on this, please assign!

**Comment by devshah207** [comment]
Can you assign me this issue please??

**Comment by Abhrajitdas02** [comment]
Can you assign me this issue please??

**Comment by UniquePratham** [comment]
Can you please assign this issue to me

**Comment by UniquePratham** [comment]
@NathanTarbert  is there any way to get Open AI API key for free, because I dont have one and its seems like Copilotkit won't work without it , I want to build this project but the API key is holding me back, please help me!

**Comment by NathanTarbert** [comment]
Hi @UniquePratham, if you set the model to 3.5 Turbo and use the free API key, it should work

**Comment by Zedoman** [comment]
@NathanTarbert can you assign this to me?

**Comment by Zedoman** [comment]
@quest-bot embark
