### ISSUE TITLE
⭐ 25 - Code Snippet Generator (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#637]
Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create a tool that suggests code snippets based on user prompts for various programming languages

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

**Comment by RohittCodes** [comment]
Hey @NathanTarbert! I would like to work on this. Can you assign it to me?
