### ISSUE TITLE
⭐ 26 - Personal Finance Advice Bot (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#638]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Build a financial advisor app that answers basic money management questions and suggests tips

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Niharika0104** [comment]
Can you assign this issue to me?

**Comment by steffy-lo** [comment]
Hi @NathanTarbert Can I work on this issue?

**Comment by afrinashar** [comment]
I would like to work on this.

**Comment by mutant138** [comment]
Can you please assign this to me also?
I am beginner I would like to work on this

**Comment by smv1256** [comment]
Can you assign me this?

**Comment by dha-stix** [comment]
Hi @NathanTarbert 
Can you assign this to me?

**Comment by NathanTarbert** [comment]
Sure thing @dha-stix ;)

**Comment by TRIPLE-ADE** [comment]
I would like to work on this, can you assign it

**Comment by smv1256** [comment]
@quest-bot embark
