### ISSUE TITLE
⭐ 27 - Content Summary Tool (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#639]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Develop a tool where users can input long-form content, and the app generates concise summaries

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by sajibAdhi** [comment]
I want to work on this, can you please assign me this issue?

**Comment by pra2107tham** [comment]
Heyy, @NathanTarbert as it seems the issue hasn't been resolved yet, I would like to contribute to this issue for my hacktoberfest. Can you please assign me

**Comment by Code-Hacker26** [comment]
Hey @NathanTarbert, I’m interested in contributing to the Content Summary Tool issue. Could you please assign it to me?

**Comment by 45hv1n** [comment]
Hello @NathanTarbert, 
I'm interested in working on this, could you please assign this issue to me

Thank you

**Comment by NathanTarbert** [comment]
@pra2107tham, even if the issue is solved we are leaving it open for now because we want to see the developer's creativity.

**Comment by JanumalaAkhilendra** [comment]
I want to work on this issue :) ,please assign it to me . 
Thank you.

**Comment by jainanuj94** [comment]
@NathanTarbert could you assign this to me as well. 

Also, is it mandatory to get assigned to issues or i can just open up the PRs for the different projects.

**Comment by NathanTarbert** [comment]
@jainanuj94, asked to be assigned, but don't close the issue when you open the PR

**Comment by shreenarayan123** [comment]
hey @NathanTarbert i would like to work on this 
can you please assign me this ?

**Comment by kom-senapati** [comment]
I would like to solve this @NathanTarbert

**Comment by princerafid01** [comment]
I am interested in this. Can you please assign me? @NathanTarbert

**Comment by kom-senapati** [comment]
@quest-bot embark
