### ISSUE TITLE
⭐ 28 - Fitness Goal Tracker (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#640]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create a tool that helps users set and track their fitness goals with daily or weekly progress reports

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Avinashs7** [comment]
Interested!

**Comment by NathanTarbert** [comment]
@Avinashs7, please follow the link at the top to get started.

**Comment by hridaya423** [comment]
@NathanTarbert can multiple people work on this or is it assignee based?

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me?

**Comment by NathanTarbert** [comment]
@hridaya423, yes, we are allowing multiple assignees

**Comment by megha-66** [comment]
can i also participate please ?

**Comment by megha-66** [comment]
@quest-bot embark
