### ISSUE TITLE
⭐ 29 - Music Lyric Finder (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#641]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Develop a bot that finds and displays lyrics to any song based on user input

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Asymtode712** [comment]
Hey @NathanTarbert , I would like to work on this, can you please assign me this issue

**Comment by NathanTarbert** [comment]
@Asymtode712, please follow the link at the top of the page to get started.

**Comment by ladaniprem** [comment]
Hey @NathanTarbert , I would like to work on this, can you please assign me this issue

**Comment by arkokundu500** [comment]
Hi @NathanTarbert , I would like to work on this , can you please **assign** me the issue.

**Comment by Asymtode712** [comment]
Hey @arkokundu500 , actually I have already been assigned this issue and I'm working on it, so you can look for other issues.

Thank you!

**Comment by AJBrownson** [comment]
@NathanTarbert 
I'd like to work on this

**Comment by akashk6697** [comment]
Hi @NathanTarbert , I would like to work on this , can you please assign me the issue.
