### ISSUE TITLE
CopilotTextarea: do not display HTTP error message as insertion/editing suggestion

### ISSUE THREAD

**Issue by ataibarkai** [CopilotKit/CopilotKit#65]
Related to yet distinct from #64 

### Proposal
Currently when the underlying LLM function returns an HTTP error, the entire error payload is displayed as the autocompletion suggestion.
Instead the error should be propagated/re-throwed, and no autocompletion text should be displayed.

### Reproduction tips
- Edit `examples/next-openai/app/api/copilotkit/chat/route.ts` to use `gpt-42` instead of `gpt-4`. 
- Run the `next-openai` example (see quickstart in the [documentation](docs.copilotkit.ai))
- Press Command-K in the CopilotTextarea in the homepage, and type an insertion prompt.

### Implementation tips
- See `use-make-standard-insertion-function.tsx`

**Comment by ataibarkai** [comment]
Fantastic @RohanMishra315 , please let me need if you need any help

**Comment by RohanMishra315** [comment]
Hey @ataibarkai Could you check the PR and do suggest !

**Comment by ataibarkai** [comment]
Taking a look, thanks @RohanMishra315 !
