### ISSUE TITLE
🚀 Feature Request: Dark theme in docs

### ISSUE THREAD

**Issue by AkashJana18** [CopilotKit/CopilotKit#651]
### 🎤 Tell us your idea

Add dark mode to the CopilotKit docs.

Working continuously on light mode is straining the eyes.

**Comment by Karush2807** [comment]
is it still open?

**Comment by KunjShah95** [comment]
can i contribute towards it

**Comment by AkashJana18** [comment]
@NathanTarbert please assign me this issue as I am already working on it.

**Comment by prathamesh424** [comment]
@NathanTarbert  please assign this to me

**Comment by B-Mustafa** [comment]
is someone working on this ?

**Comment by prathamesh424** [comment]
@NathanTarbert please assign this to me for hacktoberfest  and dev fest

**Comment by fadkeabhi** [comment]
I would like to work on this issue

**Comment by fadkeabhi** [comment]
@NathanTarbert  As this issue was unassigned I have created a pull request with implementation of dark theme. Can you took a look at it.

**Comment by Mstr-Creta** [comment]
Hey am interested

**Comment by arielweinberger** [comment]
Thanks for creating this issue! We've updated our dosc to a new docsite which supports dark mode. https://docs.copilotkit.ai
