### ISSUE TITLE
⭐ Add a CONTRIBUTING.md to Guide New Contributors

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#654]
## Issue
Add a CONTRIBUTING.md file to the CopilotKit repository.

## Expected Impact:
Adding a CONTRIBUTING.md file will help guide new contributors by providing clear instructions on how to get involved. This can enhance community engagement and streamline the contribution process.

## Suggested Content:
- Guidelines for setting up the development environment
- Steps for creating and submitting a pull request

## Example: 
https://github.com/pezzolabs/pezzo/blob/main/CONTRIBUTING.md

**Comment by SGCODEX** [comment]
Sir can you please assign me this issue instead?

**Comment by SGCODEX** [comment]
Have raised the PR Sir #662
[https://github.com/CopilotKit/CopilotKit/pull/662](url)

**Comment by ladaniprem** [comment]
Can you assign this to me? @NathanTarbert

**Comment by SandipM03** [comment]
hey, I would like to work on this issue please assign it to me.

**Comment by SGCODEX** [comment]
Please check the PR #680 Sir @NathanTarbert
