### ISSUE TITLE
⭐ Add a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#657]
## Issue
Add a CODE_OF_CONDUCT.md file to the CopilotKit repository.

## Expected Impact
Introducing a Code of Conduct will help maintain a respectful environment for all contributors. It outlines expected behaviors and procedures for handling misconduct.

## Suggested Content
- Statement of Purpose
- Expected Behavior
- Unacceptable Behavior
- Procedures for Reporting and Resolving Issues
- Consequences of Unacceptable Behavior

## Additional Context
This will align our community practices with industry standards for open-source projects.

## Example
https://github.com/defikids/defikids-dapp/blob/main/CODE_OF_CONDUCT.md

**Comment by JollyJolli** [comment]
hey there i would like to do this

**Comment by DS-Kushagra** [comment]
Can you assign this to me? @NathanTarbert

**Comment by ladaniprem** [comment]
Can you assign this to me? @NathanTarbert

**Comment by Satya900** [comment]
hey can you assign this to me

**Comment by Hiteshsambhani1** [comment]
can you assign this to me @NathanTarbert
