### ISSUE TITLE
⭐ Add a SECURITY.md File 

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#660]
## Issue
Add a SECURITY.md file to this repository

## Example 

# Security Policy

We're working hard to make CopilotKit safe and secure for everyone. Thank you for taking the time to responsibly disclose any issues you find.

All security bugs in CopilotKit should be reported by email to security@copilotkit.ai

This email address is delivered to a small security team. Your email will be acknowledged within 24 hours and please be specific with the issue you have found.

If you have not received a reply to your email within 48 hours, or have not heard from the security team for the past five days, please DM someone from CopilotKit in our [community](https://discord.com/invite/6dffbvGU3D).

Please note that our community is a public area. When escalating at this venue, please do not discuss your issue. Simply say that you’re trying to get a hold of someone from the security team.

Thank you for helping us make CopilotKit more secure.

**Comment by EveEdwin** [comment]
Adding SECURITY.md file in the repo #660

**Comment by thakurboy004** [comment]
Could you assign this issue to me under hacktoberfest2024

**Comment by mohsinansari0705** [comment]
Part of the **hacktoberfest2024**, Can you assign this to me?
