### ISSUE TITLE
📚 Documentation: Add CONTRIBUTING.md to guide contributors

### ISSUE THREAD

**Issue by AkashJana18** [CopilotKit/CopilotKit#666]
### 💬 Let us know how we can improve our documentation.

Please add CONTRIBUTING.md file so we can understand how to get started with initial setup and contribute to the actual issues.

Create a CONTRIBUTING.md file to provide contributors with instructions on how to get started with the project.
The file should include:
- A brief overview of the project
- Steps to set up the project locally
- Guidelines for reporting issues and submitting pull requests
- Information about coding standards and testing
- Any additional resources or documentation relevant to contributors
This will improve the onboarding process for new contributors and help maintain project consistency.

**Comment by prathamesh424** [comment]
hi @AkashJana18  can you assign this issue to me
