### ISSUE TITLE
⭐ Add a Pull Request Template

### ISSUE THREAD

**Issue by JeevaRamanathan** [CopilotKit/CopilotKit#669]
### 💬 Let us know how we can improve our documentation.

I think it would be helpful for both contributors and maintainers to have a pull request template, and I would like to contribute to it.

**Action Items:**
The PR template may consist of the following sections:
1. Type of contribution
2. Contributor checklist
3. Issue link
4. Description
5. Screenshots (if applicable)
6. Additional comments

I would like to know if there are any suggestions or improvements regarding this proposal.

**Comment by Shubham66020** [comment]
Tests & Review: You might want to add a section for running tests, e.g.,

**Comment by NathanTarbert** [comment]
@arielweinberger, what are your thoughts?

**Comment by Aienthu1** [comment]
Hey, @JeevaRamanathan   I am very keen to work on this issue . i am very interested to work on this. I fill very happy to you assigned me this issue .

**Comment by SOHAIB-code-png** [comment]
Hey @JeevaRamanathan please assign me this I have been facing this problem too before, I would be the ideal one  to do this
