### ISSUE TITLE
CopilotTextarea: use the document picture in the preview component

### ISSUE THREAD

**Issue by ataibarkai** [CopilotKit/CopilotKit#68]
**Describe the bug**
Relevant code component: `IncludedFilesPreview` in `included-files-preview.tsx`

CopilotTextarea allows for specifying document context,
by calling `useMakeCopilotDocumentReadable` and passing a `DocumentPointer`.

The DocumentPointer object contains an image to represent the document.

This image is used for previewing documents not yet added to the context.
But documents added to the context all show the same stock image icon.

**To Reproduce**
1. go to a CopilotTextarea.
2. Click command-K on the keyboard to bring the insertion/editing prompt
3. Write `@` to bring the available document previews
4. click a document and see its preview changing 

**Expected behavior**
The same image should be used in the pre-addition and post-addition `preview.`

**Screenshots**
<img width="706" alt="Screenshot 2023-11-02 at 3 08 32 PM" src="https://github.com/RecursivelyAI/CopilotKit/assets/746397/5e6805ed-4ab0-468a-9ba6-d821a169a411">
<img width="706" alt="Screenshot 2023-11-02 at 3 08 36 PM" src="https://github.com/RecursivelyAI/CopilotKit/assets/746397/e1f41bdb-e9be-4d94-942a-ee65339f679b">

** Browser (please complete the following information):**
 - OS / Browser [e.g. Mac / safari]

**Additional context**
Relevant code component: `IncludedFilesPreview` in `included-files-preview.tsx`

**Comment by dotslashtarun** [comment]
/attempt https://github.com/RecursivelyAI/CopilotKit/issues/68

**Comment by tarunrajput** [comment]
/attempt https://github.com/RecursivelyAI/CopilotKit/issues/68
