### ISSUE TITLE
🚀 Feature Request: Making implement in readme.md file

### ISSUE THREAD

**Issue by Piyushsahu99** [CopilotKit/CopilotKit#684]
### 🎤 Tell us your idea

I want to add information regading how to install the code zip file in the vs code .

**Comment by ZEviod** [comment]
hello @Piyushsahu99 
we can guide the installing of zip code in vs code as:

download the zip file and extract the contents to a folder 
open VS Code, and select File > open oolder to open the extracted folder OR we can directly go to folder and use Open with VSCode to open it in editor
if it's a Node.js project, run npm install or yarn install in the terminal to install dependencies
and then check package.json to check the run method either it is npm run dev or npm start and launch it

or we can add any additional instructions in the project's README to assist

**Comment by Piyushsahu99** [comment]
Sorry, For the inconvenience but this is my first time 😔

**Comment by ZEviod** [comment]
hey @Piyushsahu99 it's okay there is first time for everyone , don't be sad , it is good to ask questions and solve doubts!! stay motivated
