### ISSUE TITLE
📚 Fix Invalid Link in Readme.md for For documentation-related contributions

### ISSUE THREAD

**Issue by TejasNarkhede** [CopilotKit/CopilotKit#692]
## Description
The link for contributing to CopilotKit's contributions in the README.md file currently points to the code contributions guide.

### Steps to Reproduce
Visit the CopilotKit project README.md on GitHub.
Click the link for contributions,
Error 404

### Expected  Behavior
The contributions link should lead you to a guide specifically for contributing to CopilotKit's documentation.

### Possible Solution
Simply update the link in the [README](https://github.com/CopilotKit/CopilotKit/blob/main/README.md) to point to the correct documentation contributions guide:

**Comment by Abinanthan47** [comment]
I'd like to work on this

**Comment by ZEviod** [comment]
hi @TejasNarkhede 
first of all the link of these redirect are not correct as they led to 404 page not found
![image](https://github.com/user-attachments/assets/3c6a4dce-83e5-4b43-a20d-dd51c1caa8a0)

second we can try to reshape table of content with the details for easy guidance as we need them it's like 3 segment, first table of content leadinf to second brief link for various things like collaboration or discord server etc and then third the actual position of those things

**Comment by TejasNarkhede** [comment]
Thanks for pointing that out, @ZEviod ZEviod. It's possible that the links were working when I created the issue, but were broken due to subsequent changes to the project.

I have updated the issue

**Comment by ZEviod** [comment]
Your welcome,
 yah i also agree with you!!

**Comment by Mokshitsharma** [comment]
> ## Description
> The link for contributing to CopilotKit's contributions in the README.md file currently points to the code contributions guide.
> 
> ### Steps to Reproduce
> Visit the CopilotKit project README.md on GitHub. Click the link for contributions, Error 404
> 
> ### Expected Behavior
> The contributions link should lead you to a guide specifically for contributing to CopilotKit's documentation.
> 
> ### Possible Solution
> Simply update the link in the [README](https://github.com/CopilotKit/CopilotKit/blob/main/README.md) to point to the correct documentation contributions guide:

I'd like to work on this

**Comment by Ajit594** [comment]
> hi @TejasNarkhede first of all the link of these redirect are not correct as they led to 404 page not found ![image](https://private-user-images.githubusercontent.com/86474578/373687045-3c6a4dce-83e5-4b43-a20d-dd51c1caa8a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTMzMzQsIm5iZiI6MTcyODExMzAzNCwicGF0aCI6Ii84NjQ3NDU3OC8zNzM2ODcwNDUtM2M2YTRkY2UtODNlNS00YjQzLWEyMGQtZGQ1MWMxY2FhOGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA3MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjg5ZDI2YTNhNGIxZjRiZTljMzZlYzI0NTUxYzhmY2ZmOTlkNzUxMGVjYTBmOTMyNWM1NTEzNDk0M2FlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gM-MSqVy5BpiIV8vshlSLXdj-saWnoudRsCFUxD9L_Y)
> 
> second we can try to reshape table of content with the details for easy guidance as we need them it's like 3 segment, first table of content leadinf to second brief link for various things like collaboration or discord server etc and then third the actual position of those things

 i would like to work on this issue for DevFest AI.

**Comment by Jeevan2305** [comment]
Assign me #692

**Comment by itzpa1** [comment]
I'd love to tackle this issue. Assignment request, please.

**Comment by TejasNarkhede** [comment]
Hi @NathanTarbert, I'm unable to assign contributors to this issue. I would appreciate it if you could take a look into this.
Thank you for your time and assistance. 
 to anyone.

**Comment by NathanTarbert** [comment]
Thank you for reporting this @FaheemOnHub. 

It is fixed!
