### ISSUE TITLE
Use GPT-4-Turbo by default

### ISSUE THREAD

**Issue by ataibarkai** [CopilotKit/CopilotKit#70]
**Is your feature request related to a problem? Please describe.**
The default model should now be gpt-4-turbo

**Additional context**
Hint: look at `copilotkit/chat/route.ts`

**Comment by shuoO-24** [comment]
Hi I'm looking through this issue and trying to help with it, which version of gpt-4-turbo do we use? There are two versions `gpt-4-1106-preview` and `gpt-4-version-preview` from this table I found from [OpenAI website](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo):
<img width="809" alt="image" src="https://github.com/RecursivelyAI/CopilotKit/assets/75917985/a3538063-120f-4097-b9bf-5188450d02c6">
Also, can you assign this issue to me? I do want to contribute to this project and this looks like a good start point.
