### ISSUE TITLE
[Bug]: Get started button on the website redirects to a page not found.

### ISSUE THREAD

**Issue by South-IN** [CopilotKit/CopilotKit#705]
On the main website https://www.copilotkit.ai/  when clicking on the get started button the website open a page https://docs.copilotkit.ai/what-is-copilotkit which is not found.

**Comment by South-IN** [comment]
I can fix this issue assign it to me please.

**Comment by Git43COder** [comment]
Is anyone working on the project ?

**Comment by AkashJana18** [comment]
where is this page https://www.copilotkit.ai/ on github repositry

**Comment by SGCODEX** [comment]
I would like to work on this issue, please assign me

**Comment by arielweinberger** [comment]
Thanks for reporting! We're on it. Unfortunately, our public website is not open-source so we need to fix this internally.

**Comment by South-IN** [comment]
> Thanks for reporting! We're on it. Unfortunately, our public website is not open-source so we need to fix this internally.

Glad I could help.

**Comment by NathanTarbert** [comment]
Thank you @South-IN for reporting this!
