### ISSUE TITLE
🚀 Feature Request: Fixing the scrollbar design

### ISSUE THREAD

**Issue by saikatsardar01** [CopilotKit/CopilotKit#712]
### 🎤 Tell us your idea

![image](https://github.com/user-attachments/assets/38f2c430-bd24-4040-9e85-fce196e703f8)

The scrollbar present in this website is not looking good. It can be made more attractive that will match with this theme. 
please assign this issue to me

**Comment by VishalVinayRam** [comment]
Hey i would like to take this up .
