### ISSUE TITLE
🐛 Bug: Cards not visible in Dark Mode

### ISSUE THREAD

**Issue by sanketshinde3001** [CopilotKit/CopilotKit#713]
### ♻️ Reproduction Steps

1. Goto 'https://docs.copilotkit.ai/coagents'
...

### ✅ Expected Behavior

Cards should visible properly in Dark Mode

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/70bc028a-7b7a-4b78-b709-4a1ad7497c2b)

### 𝌚 CopilotKit Version

```shell
NA
```

### 📄 Logs (Optional)

I'm interested in solving this issue

**Comment by Tomkndn** [comment]
Want to work on the issue.

**Comment by akashk6697** [comment]
please assign this issue to me.

**Comment by Kamilkhan057** [comment]
i want to solve the problem

**Comment by akshaymishra-01** [comment]
Hi @sanketshinde3001 
I am able to fix this issue. I am looking forward for your response

**Comment by arielweinberger** [comment]
We're accepting PRs for this issue. Assignment not needed.

**Comment by sanketshinde3001** [comment]
@arielweinberger  Made PR for this . Please check this out - #724

**Comment by QaisarMoin** [comment]
Please assign me this issue
