### ISSUE TITLE
🚀 Feature Request: Implement Unit Tests for Existing Components

### ISSUE THREAD

**Issue by shubhrangipathak** [CopilotKit/CopilotKit#714]
### 🎤 Tell us your idea

I propose implementing unit tests for the existing components in the CopilotKit repository to ensure their functionality and reliability.
Unit tests will be crucial for components where user interactions occur, allowing for smoother development and maintenance.
This feature would benefit developers and contributors by providing a reliable framework for testing, facilitating easier debugging, and improving code quality.

**Comment by harshitajha4680** [comment]
I'm interested, I have found few ways to fix it, I also have the code snippet, please assign me this task!
