### ISSUE TITLE
🐛 Bug: Demo app link is broken

### ISSUE THREAD

**Issue by sanketshinde3001** [CopilotKit/CopilotKit#725]
### ♻️ Reproduction Steps

1. Goto "https://docs.copilotkit.ai/tutorials/ai-powered-textarea/overview"
2. See bug

### ✅ Expected Behavior

I should show actual app image.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/e886a5f0-1211-4f4e-ac03-d3c1cdb355e2)

### 𝌚 CopilotKit Version

```shell
NA
```

### 📄 Logs (Optional)

```shell
- Should Fix it 
- If link provided , i can fix this issue And make PR
```

**Comment by NathanTarbert** [comment]
Thank you for reporting this @sanketshinde3001!

**Comment by arielweinberger** [comment]
@sanketshinde3001 thanks for reporting - fixed!
