### ISSUE TITLE
Gracefully fail if CopilotProvider is omitted

### ISSUE THREAD

**Issue by ataibarkai** [CopilotKit/CopilotKit#73]
**Describe the bug**
Virtually every CopilotKit functionality depends on a CopilotContext provided by the CopilotProvider.
e.g. CopilotTextarea autocompletions, chatbot, etc.

However when a CopilotProvider does not wrap the component, functionality fails silently.

**To Reproduce**
1. Omit `<CopilotProvider>...</CopilotProvider>`
2. trigger `useMakeCopilotReadable`, `useMakeCopilotActionable`, `CopilotTextarea`, `CopilotSidebarUIProvider`
3. See how functionality does not work, but no error is emitted

**Expected behavior**
An error is emitted, with clear description of the likely core issue and how to resolve it (namely, wrap the app in a CopilotProvider). Point to docs.

**Comment by Suraj-Bhandarkar-S** [comment]
I would like to take a look at this if its still available.
