### ISSUE TITLE
🚀 Feature Request: Add "Go to Top" Button on the Home Screen

### ISSUE THREAD

**Issue by Mefisto04** [CopilotKit/CopilotKit#745]
### 🎤 Tell us your idea

Add a "Go to Top" button on the home screen that allows users to quickly return to the top of the page with a single click. This button would appear after the user scrolls down and remain fixed at the bottom right corner of the screen for easy access.

This feature is particularly useful for users navigating through long lists or content on the home screen. Instead of manually scrolling back to the top, they can simply click the button, enhancing user experience and efficiency.

**Comment by akshaymishra-01** [comment]
Hello @Mefisto04 I am very much interested to work on this issue. Can you assign this issue to me? 
I am looking forward to your response.
Thank You!

**Comment by Mefisto04** [comment]
please find other issue @akshaymishra-01, i want to contribute in this

**Comment by varun1455** [comment]
Hi, I want to contribute to this. Please assign me this issue
