### ISSUE TITLE
⭐ 37 - Home or Business Energy Planner (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#784]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

 💡 Please show your support and give a ⭐ to the CopilotKit repository.

#### Documentation to: 
- [CopilotKit](https://docs.copilotkit.ai/)
- [CopilotKit CoAgents](https://docs.copilotkit.ai/coagents) (Advanced)

### Description of app functionality:
Develop a tool that helps users plan energy-efficient solutions for their homes or businesses using AI agents for guidance.

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by vr-varad** [comment]
Hey @NathanTarbert I would like to work on this issue:)

@quest-bot embark

**Comment by Dkghuser** [comment]
Hello @NathanTarbert , I would like to contribute to this issue. Please assign this issue to me.

Thank you.

**Comment by naaa760** [comment]
Hello @NathanTarbert :)
I want to contribute to this issue. Please assign this issue to me.
Thankyou!
