### ISSUE TITLE
⭐ 38 - History Research Assistant (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#785]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

 💡 Please show your support and give a ⭐ to the CopilotKit repository.

#### Documentation to: 
- [CopilotKit](https://docs.copilotkit.ai/)
- [CopilotKit CoAgents](https://docs.copilotkit.ai/coagents) (Advanced)

### Description of app functionality:
Create an interactive platform where users explore historical events, with AI agents providing explanations, timelines, and answering questions.

The App will: 
- Show events in a timeline (map)
- Add new events to the timeline

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by sanketshinde3001** [comment]
Interested

**Comment by Venkateeshh** [comment]
Im interested

**Comment by Venkateeshh** [comment]
@quest-bot embark
