### ISSUE TITLE
⭐ 41 - Flight Booking App (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#788]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

 💡 Please show your support and give a ⭐ to the CopilotKit repository.

#### Documentation to: 
- [CopilotKit](https://docs.copilotkit.ai/)
- [CopilotKit CoAgents](https://docs.copilotkit.ai/coagents) (Advanced)

### Description of app functionality:
Develop a platform where users can browse flight details using a mock database or API and book a flight using an AI agent.

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by Malayt04** [comment]
Hello @NathanTarbert,
I'm interested in working on this, could you please assign this issue to me?

Thank you

**Comment by Mwesigwa12** [comment]
Hello
I'd also love to attempt this

**Comment by eliezerjoel** [comment]
Hello Asign me too
I'm working on it

**Comment by heysagnik** [comment]
Hey @NathanTarbert ,I am interested please assign me
