### ISSUE TITLE
⭐ 42 - Legal Document Reviewer (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by NathanTarbert** [CopilotKit/CopilotKit#789]
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

 💡 Please show your support and give a ⭐ to the CopilotKit repository.

#### Documentation to: 
- [CopilotKit](https://docs.copilotkit.ai/)
- [CopilotKit CoAgents](https://docs.copilotkit.ai/coagents) (Advanced)

### Description of app functionality:
Develop a system where AI agents analyze legal documents, highlight important sections, and suggest revisions to ensure compliance and clarity.

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

![Swag_2](https://github.com/user-attachments/assets/d120bf97-95af-40a6-8618-6fb6a9198696)

**Comment by TRIPLE-ADE** [comment]
I am interested in this can you assign it to me

**Comment by ARYPROGRAMMER** [comment]
hey @NathanTarbert I can work on this

**Comment by Dkghuser** [comment]
@quest-bot embark

**Comment by naaa760** [comment]
@quest-bot embark

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , please assign this task to me.

**Comment by heysagnik** [comment]
Hey @NathanTarbert assign it to me

**Comment by JeevaRamanathan** [comment]
@quest-bot embark

**Comment by anshuman-rai-27** [comment]
hey can you plz assign me this issue ?
