### ISSUE TITLE
🐛 Bug: Textarea Autosuggestions Not Fetching Suggestions When Typing

### ISSUE THREAD

**Issue by ramonmalcolm10** [CopilotKit/CopilotKit#890]
### ♻️ Reproduction Steps

1. Go to the feature/page where the textarea with autosuggestions is located.
2. Begin typing into the textarea.
3. Observe that no network requests or function calls are made to retrieve suggestions.

### ✅ Expected Behavior

As the user types in the textarea, there should be calls to retrieve relevant suggestions based on the input, which should then be displayed in the textarea.

### ❌ Actual Behavior

 No network requests or API calls are made, and no suggestions are provided as the user types.

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/react-core@1.3.11
├── @copilotkit/react-textarea@1.3.11
├── @copilotkit/runtime@1.3.11
```

**Comment by NathanTarbert** [comment]
Hi @ramonmalcolm10, thank you for flagging this. We are looking into this and will get back to you when I hear back from engineering.

**Comment by ramonmalcolm10** [comment]
@NathanTarbert I did some checks and it's working on Next.js 14 and not working on version 15 with React 19rc.

**Comment by NathanTarbert** [comment]
Ok, that makes sense. We don't officially support Next.js 15 yet because it is bundled with React 19, which is not GA yet. 

When React 19 is generally available, we will support Next.js 15
