### ISSUE TITLE
📚 Documentation: Fix Import Statement for OpenAI: Use Named Import Instead of Default Import

### ISSUE THREAD

**Issue by Kwesi-dev** [CopilotKit/CopilotKit#894]
### 💬 Let us know how we can improve our documentation.

https://docs.copilotkit.ai/quickstart

**Where can this issue be found**
This issue can be found under Endpoint setup. The code snippet is as follows:
 `import OpenAI from 'openai';`

**Why this change**
OpenAI is not exported as default from openai. This leads to a typescript warning.

**Comment by AravindAkuthota** [comment]
@Kwesi-dev  can you assign to me i would work on it

**Comment by NathanTarbert** [comment]
@AravindAkuthota, yes please go ahead and work on it.
