### ISSUE TITLE
🐛 Bug: missing packageManager field in package.json

### ISSUE THREAD

**Issue by ChiragAgg5k** [CopilotKit/CopilotKit#988]
### ♻️ Reproduction Steps

1. Follow the `CONTRIBUTING.md` guidelines
2. Install dependencies using `pnpm`
3. run `turbo run build`
...

### ✅ Expected Behavior

Should run the build process with no issues.

### ❌ Actual Behavior

Gives error:

<img width="511" alt="Screenshot 2024-11-28 at 11 36 50 AM" src="https://github.com/user-attachments/assets/0cef45da-78f3-40b9-879e-667eb220bd32">

### 𝌚 CopilotKit Version

```shell
Using the latest copilotkit fork.
```

**Comment by ChiragAgg5k** [comment]
The fix is pretty simple and i would like to work on it

**Comment by officialrobert** [comment]
@ChiragAgg5k I wonder if this error gets fixed when you run `turbo run build` from `CopilotKit\CopilotKit`

so just 
```
cd CopilotKit
```
